#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_nanahi")]
public partial class BDConxDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertUsuarios(Usuarios instance);
  partial void UpdateUsuarios(Usuarios instance);
  partial void DeleteUsuarios(Usuarios instance);
  #endregion
	
	public BDConxDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_nanahiConS"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BDConxDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BDConxDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BDConxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BDConxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Usuarios> Usuarios
	{
		get
		{
			return this.GetTable<Usuarios>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdUsuario;
	
	private string _Nombre;
	
	private string _Apellido;
	
	private string _Correo;
	
	private string _Password;
	
	private int _IdEstadoUsuario;
	
	private int _IdTipoUsuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIdEstadoUsuarioChanging(int value);
    partial void OnIdEstadoUsuarioChanged();
    partial void OnIdTipoUsuarioChanging(int value);
    partial void OnIdTipoUsuarioChanged();
    #endregion
	
	public Usuarios()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdUsuario
	{
		get
		{
			return this._IdUsuario;
		}
		set
		{
			if ((this._IdUsuario != value))
			{
				this.OnIdUsuarioChanging(value);
				this.SendPropertyChanging();
				this._IdUsuario = value;
				this.SendPropertyChanged("IdUsuario");
				this.OnIdUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Apellido
	{
		get
		{
			return this._Apellido;
		}
		set
		{
			if ((this._Apellido != value))
			{
				this.OnApellidoChanging(value);
				this.SendPropertyChanging();
				this._Apellido = value;
				this.SendPropertyChanged("Apellido");
				this.OnApellidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string Correo
	{
		get
		{
			return this._Correo;
		}
		set
		{
			if ((this._Correo != value))
			{
				this.OnCorreoChanging(value);
				this.SendPropertyChanging();
				this._Correo = value;
				this.SendPropertyChanged("Correo");
				this.OnCorreoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoUsuario", DbType="Int NOT NULL")]
	public int IdEstadoUsuario
	{
		get
		{
			return this._IdEstadoUsuario;
		}
		set
		{
			if ((this._IdEstadoUsuario != value))
			{
				this.OnIdEstadoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._IdEstadoUsuario = value;
				this.SendPropertyChanged("IdEstadoUsuario");
				this.OnIdEstadoUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoUsuario", DbType="Int NOT NULL")]
	public int IdTipoUsuario
	{
		get
		{
			return this._IdTipoUsuario;
		}
		set
		{
			if ((this._IdTipoUsuario != value))
			{
				this.OnIdTipoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._IdTipoUsuario = value;
				this.SendPropertyChanged("IdTipoUsuario");
				this.OnIdTipoUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
